# [LAB-05] 4. 결측치 처리

## #01. 준비작업

### 1. 패키지 설치

scikit-learn 패키지의 설치가 필요하다.

In [2]:
!pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\ITWILL\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\ITWILL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\ITWILL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\ITWILL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\ITWILL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.18.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\ITWILL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### 2. 라이브러리 참조

In [3]:
import numpy as np
from jussam import load_data
from pandas import DataFrame
from sklearn.impute import SimpleImputer

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 3. 데이터 가져오기

In [4]:
origin = load_data("ref_sample")
origin

📚 데이터 정제를 위한 실습용 데이터

        kor  eng   math    sic
name
철수   98.000   77 88.000 64.000
영희   88.000  120 62.000 72.000
민철      NaN   70 83.000 79.000
수현   63.000   60 31.000 71.000
호영   75.000   50 90.000    NaN
영호   80.000   88 91.000 72.000
용식   82.000   88    NaN 90.000
나영   90.000   92 81.000    NaN
석영   91.000   90 89.000 80.000

## #02. 결측치 확인하기

### 1. 결측치 여부 확인

각 열에 대해 결측치가 아닐 경우 `False`, 결측치는 `True`로 표시됨

`isna()` 함수도 같은 기능

In [5]:
empty = origin.isnull()
empty

        kor    eng   math    sic
name
철수    False  False  False  False
영희    False  False  False  False
민철     True  False  False  False
수현    False  False  False  False
호영    False  False  False   True
영호    False  False  False  False
용식    False  False   True  False
나영    False  False  False   True
석영    False  False  False  False

### 2. 각 열별로 결측치의 수를 확인

`isnull()` 혹은 `isna()`의 결과에 대한 합계를 구한다.

`True=1`, `False=0`

In [6]:
empty.sum()

kor     1
eng     0
math    1
sic     2
dtype: int64

## #03. 결측치 소거

### 1. 행 단위 삭제

결측치가 있는 모든 행 삭제 (원본은 변화 없음, 삭제 결과가 리턴됨)

`inplace=True` 파라미터를 적용할 경우 원본에 즉시 반영되고 리턴값 없음

In [7]:
na1 = origin.dropna()
na1

        kor  eng   math    sic
name
철수   98.000   77 88.000 64.000
영희   88.000  120 62.000 72.000
수현   63.000   60 31.000 71.000
영호   80.000   88 91.000 72.000
석영   91.000   90 89.000 80.000

### 2. 열 단위 삭제

`dropna()` 메서드에 `axis=1` 파라미터를 적용한다. (`기본값=0`)

In [8]:
na2 = origin.dropna(axis=1)
na2

      eng
name
철수     77
영희    120
민철     70
수현     60
호영     50
영호     88
용식     88
나영     92
석영     90

### 3. 특정 열에 대해서만 결측치가 존재하는 행 삭제

In [9]:
#kor열에 존재하는 행 삭제
na3 = origin.dropna(subset=['kor'])
na3

        kor  eng   math    sic
name
철수   98.000   77 88.000 64.000
영희   88.000  120 62.000 72.000
수현   63.000   60 31.000 71.000
호영   75.000   50 90.000    NaN
영호   80.000   88 91.000 72.000
용식   82.000   88    NaN 90.000
나영   90.000   92 81.000    NaN
석영   91.000   90 89.000 80.000

## #04. 결측치 대체

### 1. 고정값으로 대체

모든 결측치를 동일한 값으로 교체

원본은 변화 없음, 삭제결과 리턴됨

`inplace=True`를 적용할 경우 원본에 즉시 반영되고 리턴값 없음

In [10]:
re_df1 = origin.fillna(value=50)
re_df1

        kor  eng   math    sic
name
철수   98.000   77 88.000 64.000
영희   88.000  120 62.000 72.000
민철   50.000   70 83.000 79.000
수현   63.000   60 31.000 71.000
호영   75.000   50 90.000 50.000
영호   80.000   88 91.000 72.000
용식   82.000   88 50.000 90.000
나영   90.000   92 81.000 50.000
석영   91.000   90 89.000 80.000

### 2. 통계적 값으로 대체 (1) - 결측치를 정제할 규칙을 담고 있는 객체 생성

각 열단위로 평균`(strategy='mean')`을 결측치`(missing_values)`에 지정

strategy 옵션 : mean=평균, median=중앙값, most_frequent: 최빈값(가장 많이 관측되는 수)

> 이 객체의 생성이 결측치를 즉시 처리했다는 것을 의미하는 것은 아니다.

In [11]:
imr = SimpleImputer(missing_values=np.nan, strategy='mean')

### 3. 통계적 값으로 대체 (2) - 생성된 규칙을 적용

결측치가 정제된 2차원 배열로 리턴되므로 다시 DataFrame으로 재구성할 필요가 있다.

In [12]:
df_imr = imr.fit_transform(origin.values)
df_imr

array([[ 98.        ,  77.        ,  88.        ,  64.        ],
       [ 88.        , 120.        ,  62.        ,  72.        ],
       [ 83.375     ,  70.        ,  83.        ,  79.        ],
       [ 63.        ,  60.        ,  31.        ,  71.        ],
       [ 75.        ,  50.        ,  90.        ,  75.42857143],
       [ 80.        ,  88.        ,  91.        ,  72.        ],
       [ 82.        ,  88.        ,  76.875     ,  90.        ],
       [ 90.        ,  92.        ,  81.        ,  75.42857143],
       [ 91.        ,  90.        ,  89.        ,  80.        ]])

### 4. 통계적 값으로 대체 (3) - 결측치 정제 결과를 DataFrame으로 재구성

In [13]:
re_df2 = DataFrame(df_imr,
                   index=origin.index,
                   columns=origin.columns
                   )
re_df2

        kor     eng   math    sic
name
철수   98.000  77.000 88.000 64.000
영희   88.000 120.000 62.000 72.000
민철   83.375  70.000 83.000 79.000
수현   63.000  60.000 31.000 71.000
호영   75.000  50.000 90.000 75.429
영호   80.000  88.000 91.000 72.000
용식   82.000  88.000 76.875 90.000
나영   90.000  92.000 81.000 75.429
석영   91.000  90.000 89.000 80.000

### 5. 특정 컬럼 하나만 처리하기 (1)- 컬럼의 값만 추출한 후 n행1열로 재구성

- sklearn의 SimpleInputer는 파라미터로 2차 배열을 요구한다.
- 특정 컬럼 하나에 대해서만 결측치 대체를 수행해야 할 경우    
  sklearn의 요구사항에 맞춰 n행 1열로 재구성해야 한다.

In [14]:
reshape = origin['kor'].values.reshape(-1,1)
reshape

array([[98.],
       [88.],
       [nan],
       [63.],
       [75.],
       [80.],
       [82.],
       [90.],
       [91.]])

### 6. 특정 컬럼의 값 하나만 처리하기 (2) - 결측치 처리하기

In [15]:
reshape_imr = imr.fit_transform(reshape)
reshape_imr

array([[98.   ],
       [88.   ],
       [83.375],
       [63.   ],
       [75.   ],
       [80.   ],
       [82.   ],
       [90.   ],
       [91.   ]])

### 7. 특정 컬럼의 값 하나만 처리하기 (3) - 결측치 처리 결과를 DataFrame의 컬럼에 적용하기

In [16]:
특정컬럼_정제df = origin.copy()
특정컬럼_정제df['kor'] = reshape_imr
특정컬럼_정제df

        kor  eng   math    sic
name
철수   98.000   77 88.000 64.000
영희   88.000  120 62.000 72.000
민철   83.375   70 83.000 79.000
수현   63.000   60 31.000 71.000
호영   75.000   50 90.000    NaN
영호   80.000   88 91.000 72.000
용식   82.000   88    NaN 90.000
나영   90.000   92 81.000    NaN
석영   91.000   90 89.000 80.000

In [ ]:
# 연습문제
# 안녕하세요, 데이터 분석가님
# 최근 한달간의 판매 기록(month_sales)을 받았는데, 아쉽게도 일부 데이터가 누락되었습니다.
# 정확한 월말 매출 보고를 위해 분석가님의 도움이 필요합니다.
# 아래의 미션을 순서대로 해결하여 데이터 정제를 완료.
# 미션1 : 데이터 탐색
#   데이터를 불러온 후 각 열(column)에 몇 개의 결측치 (missing value)가 있는지 확인해주세요.
# 미션2 : 신뢰할 수 없는 데이터 제거
#   'Quantity'(수량) 정보가 누락된 데이터는 주문 과정에서 오류가 있었을 가능성이 높습니다.
#   이 데이터는 분석에서 제외하기로 결정했습니다.
#    'Quantity'열에 결측치가 있는 모든 행(row)을 삭제해주세요.
# 미션3 : 가격 정보 복원
#   일부 제품의 'Price' (가격) 정보가 누락되었습니다.
#   해당 제품들은 'Price' 열의 전체 평균 가격으로 값을 채워 넣어 데이터를 복원해주세요.

In [31]:
# 0. 파일 불러오기 및 정보 확인
MS = load_data('month_sales')
MS.info()
MS
# 미션 1. 데이터 탐색
MS_empty = MS.isnull()
MS_empty.sum()
# 미션2. 신뢰할 수 없는 데이터 제거
MS_Quantity = MS.dropna(subset=['Quantity'])
MS_Quantity
# 미션3. 가격 정보 복원
MS_reshape = MS_Quantity['Price'].values.reshape(-1,1)
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
MS_imr = imr.fit_transform(MS_reshape)

MS_price = MS_Quantity.copy()
MS_price['Price'] = MS_imr
MS_price

📚 데이터 정제(결측치 처리) 연습문제용 데이터

    field     description
--  --------  ----------------
 0  OrderID   주문번호(인덱스)
 1  Product   상품명
 2  Category  상품 카테고리
 3  Price     단가
 4  Quantity  주문 수량

<class 'pandas.DataFrame'>
Index: 10 entries, 1001 to 1010
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   10 non-null     str
 1   Category  10 non-null     str
 2   Price     8 non-null      float64
 3   Quantity  7 non-null      float64
dtypes: float64(2), str(2)
memory usage: 558.0 bytes

          Product     Category    Price  Quantity
OrderID
1001       Laptop  Electronics 1200.000    10.000
1003     Keyboard  Electronics  339.000     5.000
1004      Monitor  Electronics  300.000     8.000
1006         Desk    Furniture  150.000     3.000
1007        Chair    Furniture  339.000     2.000
1008         Lamp    Furniture   40.000    15.000
1009     Notebook   Stationery    5.000   100.000

# 미션3번 다시확인