# [LAB 04] 1. 데이터 구조 점검 (1)

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data        # 데이터 로딩 함수
from pandas import CategoricalDtype # 명목형 타입 클래스

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [2]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 확인하기

### 1. 데이터의 크기

In [4]:
rows, columns = origin.shape
print("%d행,%d열의 %d차원 데이터" %(rows, columns, origin.ndim))

9행,6열의 2차원 데이터

### 2. 각 변수의 데이터 타입 확인

In [6]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

## #03. 데이터 타입 변경

### 1. 작업을 위한 복사본 생성

In [8]:
컬럼타입변경df = origin.copy() #복사본으로 해야한다
컬럼타입변경df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### 2. 컬럼 단위 변경

- **컬럼 단위의 데이터 타입 변경**
  - 하나의 컬럼은 시리즈 개체이므로 `astype()` 함수로 타입 변경 가능.
  - 변경된 결과는 다시 원래의 컬럼에 저장해야 DataFrame에 반영된다.

In [9]:
컬럼타입변경df['국어'] = 컬럼타입변경df['국어'].astype('float')
컬럼타입변경df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      float64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: float64(1), int64(4), str(1)
memory usage: 612.0 bytes

### 3. 타입 일괄 변경 후 새로운 DataFrame 리턴 받기

- **타입 변환 적용**
  - 타입 변환을 수행할 변수만 `이름:타입` 형식의 딕셔너리로 구성한다.
  - 결과가 적용된 복사본이 리턴된다.

In [13]:
타입변환df = origin.astype({'국어': 'float', '영어': 'float', '수학': 'float', '과학': 'bool'})
타입변환df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      float64
 3   영어      9 non-null      float64
 4   수학      9 non-null      float64
 5   과학      9 non-null      bool
dtypes: bool(1), float64(3), int64(1), str(1)
memory usage: 549.0 bytes

### 4. 타입 변환 전 원본 확인

- DataFrame 객체에 대한 `astype()`함수는 결과가 적용된 복사본을 리턴한다.     
  (원본은 변하지 않음)

In [14]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### 5. 범주형 데이터를 명목척도로 변환 (1)

- 컬럼 단위 변환

In [15]:
컬럼단위_명목df = origin.copy()
컬럼단위_명목df['학년'] = 컬럼단위_명목df['학년'].astype('category')
컬럼단위_명목df['성별'] = 컬럼단위_명목df['성별'].astype('category')
컬럼단위_명목df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      category
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(2), int64(4)
memory usage: 493.0 bytes

### 6. 범주형 데이터를 명목척도로 변환 (2)

- DataFrame 전체에 적용 후 복사본 리턴 받기

In [16]:
범주형df = origin.astype({'학년': 'category', '성별': 'category'})
범주형df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      category
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(2), int64(4)
memory usage: 493.0 bytes

### 7. 범주형 데이터를 서열척도로 변환 (1)

- **컬럼 단위로 적용하여 원본에 직접 적용하기**
  - `CategoricalDtype` 클래스의 객체를 생성하여 범주의 특성을 설정한다.

In [18]:
컬럼단위_서열척도df = origin.copy()
컬럼단위_서열척도df['학년'] = 컬럼단위_서열척도df['학년'].astype(
    CategoricalDtype(categories=[1,2,3,4], ordered=True))
컬럼단위_서열척도df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(1), int64(4), str(1)
memory usage: 753.0 bytes

### 8. 범주형 데이터를 서열척도로 변환 (2)

- DataFrame 전체에 적용 후 복사본 반환 받기

In [19]:
서열척도_변환df = origin.astype({
    "학년" : CategoricalDtype(categories=[1,2,3,4], ordered=True)})
서열척도_변환df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(1), int64(4), str(1)
memory usage: 753.0 bytes

## #04. 행, 열의 이름 변경

### 1. `rename()` 메서드의 사용

-  `기존이름: 새이름` 형식의 딕셔너리로 지정
-  `columns`와 `index`중 변경을 원하는 파라미터 하나만 설정 가능.
-  원본은 변화 없음. 결과가 적용된 복사본이 생성된다.
-  이름이 변경되지 않은 항목이 결과에서 제외되지는 않는다.
-  원본에 즉시 반영해야 할 경우 `inplace=True` 파라미터를 적용

In [20]:
이름변경df = origin.rename(
    columns={'국어': 'kor', '영어': 'eng', '수학': 'math', '과학': 'sci'},
    index={'석영': 'suk', '호영': 'ho', '민철': 'min', '수현': 'su'})
이름변경df

     학년  성별  kor  eng  math  sci
이름
철수    1  남자   98   77    88   64
영희    2  여자   88  120    62   72
min   1  남자   92   70    83   79
su    3  여자   63   60    31   71
ho    4  남자   75   50    90   88
영호    4  남자   80   88    91   72
용식    2  남자   82   88    79   90
나영    1  여자   90   92    81   95
suk   1  남자   91   90    89   80

In [ ]:
# 연습문제1. 과일 가게 매출 기록 정리하기
# 친한 친구가 작은 과일 가게를 운영하기 시작했습니다.
# 친구는 매일의 판매 기록을 수첩에 손으로 적어두었는데,
# 이제 체계적인 데이터 관리를 위해 당신에게 도움을 요청했습니다.
# 친구가 어설프게 만든 초기 데이터셋의 이름은 fruit_shop입니다.
# 1. 데이터는 총 몇 행, 몇 열로 구성되어 있는지와 각 변수의 데이터 타입을 확인하세요
# 2. 데이터의 변수 이름을 살펴보니 Num_Sold만 영어로 되어 있습니다. 일관성을 위해 '판매량'으로 변경하세요.
# 3. 데이터 타입 확인 결과 몇 가지 타입을 더 효율적으로 변경해야 할 것 같습니다. 아래의 두 가지 타입 변환을 한번에 일괄 처리 하세요.
#    1) '과일'열은 과일의 종류가 반복됩니다. 메모리 효율을 위해 일반 문자열 타입이 아닌 명목형 데이터로 변경하세요.
#    2) '등급'열은 과일의 품질을 나타내며, 'A','B','C'사이에는 순서(A<B<C)가 있습니다. 이를 적합한 데이터 타입으로 변경하세요.
# 4. 전처리가 완료된 최종 데이터 셋의 정보를 다시 확인하세요.

In [23]:
# 0. 파일 로드 및 정보확인
fruit = load_data('fruit_shop')
fruit.info()
fruit

📚 어느 과일 가게의 매출을 정리한 가상의 데이터(인덱스와 메타데이터 없음)
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   판매일       12 non-null     int64
 1   과일        12 non-null     str
 2   등급        12 non-null     str
 3   가격        12 non-null     int64
 4   Num_Sold  12 non-null     int64
dtypes: int64(3), str(2)
memory usage: 717.0 bytes

    판매일   과일 등급    가격  Num_Sold
0     1   사과  A  1500        10
1     1  바나나  B  1000        15
2     1   사과  B  1200         5
3     2  복숭아  A  2500         8
4     2  바나나  A  1200        12
5     2   사과  C  1000        20
6     3   사과  A  1500        12
7     3  복숭아  B  2200        10
8     3  바나나  B  1000        18
9     4  바나나  A  1200        20
10    4   사과  B  1200        11
11    4  복숭아  A  2500        15

In [34]:
# 1. 데이터는 총 몇 행, 몇 열로 구성
rows, columns = fruit.shape
print("총 %d행 %d열로 구성되어있습니다." %(rows, columns))

# 2. 데이터의 변수 이름을 살펴보니 Num_Sold만 영어로 되어있습니다. 데이터의 일관성을 위해'판매량'으로 변경하세요
이름변경fruit = fruit.rename(
    columns={"Num_Sold": "판매량"})
이름변경fruit.info()

# 3. 데이터 타입 확인 결과 몇 가지 타입을 더 효율적으로 변경해야 할 것 같습니다. 아래의 두 가지 타입 변환을 한번에 일괄 처리 하세요.
#    1) '과일'열은 과일의 종류가 반복됩니다. 메모리 효율을 위해 일반 문자열 타입이 아닌 명목형 데이터로 변경하세요.
#    2) '등급'열은 과일의 품질을 나타내며, 'A','B','C'사이에는 순서(A<B<C)가 있습니다. 이를 적합한 데이터 타입으로 변경하세요.
명목형fruit = 이름변경fruit.astype({'과일': 'category'}, CategoricalDtype(categories=['A','B','C'], ordered=True))
명목형fruit.info()
print(명목형fruit)
# 4. 전처리가 완료된 최종 데이터 셋의 정보를 다시 확인하세요.

총 12행 5열로 구성되어있습니다.
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판매일     12 non-null     int64
 1   과일      12 non-null     str
 2   등급      12 non-null     str
 3   가격      12 non-null     int64
 4   판매량     12 non-null     int64
dtypes: int64(3), str(2)
memory usage: 717.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판매일     12 non-null     int64
 1   과일      12 non-null     category
 2   등급      12 non-null     str
 3   가격      12 non-null     int64
 4   판매량     12 non-null     int64
dtypes: category(1), int64(3), str(1)
memory usage: 589.0 bytes
    판매일   과일 등급    가격  판매량
0     1   사과  A  1500   10
1     1  바나나  B  1000   15
2     1   사과  B  1200    5
3     2  복숭아  A  2500    8
4     2  바나나  A  1200   12
5     2   사과  C  1000   20
6     3   사과  A  1500   12
7     3  복숭아  B  2200   10
8     3  바나나  B  1000   18
9     4  바나나  A  1200   20
10    4   사과  B  1200   11
11    4  복숭아  A  2500   15

C:\Users\ITWILL\AppData\Local\Temp\ipykernel_18736\547993109.py:13: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  명목형fruit = 이름변경fruit.astype({'과일': 'category'}, CategoricalDtype(categories=['A','B','C'], ordered=True))

In [13]:
# 네 종류의 식단 A1, A2, A3, A4에 따른 식이용법이 혈액응고시간에 영향을 주는지 알고자 실험한 자료다 다음과 같다
# 인자의 수준을 나타내는 변수를 class로, 실습값을 time으로 하여 데이터를 구성하여라.
# class는 명목형 변수이다.

from pandas import DataFrame

혈액응고시간DF = {
    "Class" : ["A1", "A1", "A1", "A1", "A1",
               "A2", "A2", "A2", "A2", "A2", "A2",
                "A3", "A3", "A3", "A3", "A3", "A3", "A3",
                 "A4", "A4", "A4", "A4", "A4", "A4", "A4"],

    "time" : [62, 60, 63, 59, 61,
              62, 67, 71, 64, 65, 66,
              68, 66, 71, 67, 68, 69, 70, 
              58, 62, 60, 59, 61, 63, 64]
}
DF = DataFrame(혈액응고시간DF)
DF

   Class  time
0     A1    62
1     A1    60
2     A1    63
3     A1    59
4     A1    61
5     A2    62
6     A2    67
7     A2    71
8     A2    64
9     A2    65
10    A2    66
11    A3    68
12    A3    66
13    A3    71
14    A3    67
15    A3    68
16    A3    69
17    A3    70
18    A4    58
19    A4    62
20    A4    60
21    A4    59
22    A4    61
23    A4    63
24    A4    64