# [LAB 04] 2. 데이터 구조 점검 (2)

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data
from pandas import Series

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [2]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 행,열 재배치

### 1. 열 순서 변경

- 지정된 순서대로 열이 재정렬 된 결과가 반환된다.(`inplace` 파라미터 지원 안함)
- 원본은 변화 없음. 결과가 적용된 복사본이 생성된다.
- 재배치 되지 못한 열은 제외된다.

In [3]:
열순서변경DF = origin.reindex(columns=['국어', '수학', '과학', '영어'])
열순서변경DF

    국어  수학  과학   영어
이름
철수  98  88  64   77
영희  88  62  72  120
민철  92  83  79   70
수현  63  31  71   60
호영  75  90  88   50
영호  80  91  72   88
용식  82  79  90   88
나영  90  81  95   92
석영  91  89  80   90

### 2. 행 순서 변경

- 지정된 순서대로 행이 재정렬 된 결과가 반환된다.
- 원본은 변화 없음. 결과가 적용된 복사본이 생성된다.
- 재배치 되지 못한 행은 제외된다.

In [4]:
행순서변경DF = origin.reindex(index=['석영', '호영', '민철', '수현'])
행순서변경DF

    학년  성별  국어  영어  수학  과학
이름
석영   1  남자  91  90  89  80
호영   4  남자  75  50  90  88
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  71

## #03. 행 추가하기

### 1. 리스트로 행 추가하기

- 추가될 행의 인덱스 이름을 지정해야 한다.
- 리스트로 추가할 경우 DataFrame의 컬럼 순서에 맞게 지정해야 한다.
- 누락되는 값이 있거나 값의 수가 초과할 경우 에러

In [5]:
리스트행추가DF = origin.copy()
리스트행추가DF.loc['정호'] = [2, '남자', 90, 80, 70, 60]
리스트행추가DF

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
정호   2  남자  90   80  70  60

### 2. 딕셔너리로 추가하기

-   컬럼 순서는 상관 없다.
-   누락되는 값이 있거나 값의 수가 초과할 경우 에러

In [7]:
딕셔너리행추가DF = origin.copy()
딕셔너리행추가DF.loc['민정'] = {"학년": 4, "성별": "여자", "국어": 81, "영어": 72, "수학": 84, "과학": 90}
딕셔너리행추가DF

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
민정   4  여자  81   72  84  90

### 3. Series 객체로 행 추가하기

- 순서는 상관 없다.
- Series 객체의 index가 DataFrame의 변수명과 동일해야 한다.

In [8]:
시리즈행추가DF = origin.copy()
s = Series([2, "남자", 90, 80, 70, 60],
           index=["학년", "성별", "국어", "영어", "수학", "과학"])
시리즈행추가DF.loc['형석'] = s
시리즈행추가DF

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
형석   2  남자  90   80  70  60

### 4. 빈 값을 포함하는 행 추가하기

- 데이터를 추가할 때 값이 없는 필드는 생략할 수 있다.
- Series 형태의 객체로 추가할 때만 가능함

In [9]:
빈값포함추가DF = origin.copy()
d = Series([2, "남자", 93, 71],
           index=["학년", "성별", "국어", "수학"])
빈값포함추가DF.loc['석호'] = d
빈값포함추가DF

    학년  성별  국어      영어  수학     과학
이름
철수   1  남자  98  77.000  88 64.000
영희   2  여자  88 120.000  62 72.000
민철   1  남자  92  70.000  83 79.000
수현   3  여자  63  60.000  31 71.000
호영   4  남자  75  50.000  90 88.000
영호   4  남자  80  88.000  91 72.000
용식   2  남자  82  88.000  79 90.000
나영   1  여자  90  92.000  81 95.000
석영   1  남자  91  90.000  89 80.000
석호   2  남자  93     NaN  71    NaN

### 5. 기존의 행을 복사해서 행 추가 하기

In [11]:
기존행복사DF = origin.copy()
기존행복사DF.loc['철민'] = 기존행복사DF.loc['철수']
기존행복사DF

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
철민   1  남자  98   77  88  64

### 6. 단일 값으로 행 추가하기

- 모든 변수에 같은 값이 저장된다.

In [12]:
단일값추가DF = origin.copy()
단일값추가DF.loc['희영'] = 100
단일값추가DF

     학년   성별   국어   영어   수학   과학
이름
철수    1   남자   98   77   88   64
영희    2   여자   88  120   62   72
민철    1   남자   92   70   83   79
수현    3   여자   63   60   31   71
호영    4   남자   75   50   90   88
영호    4   남자   80   88   91   72
용식    2   남자   82   88   79   90
나영    1   여자   90   92   81   95
석영    1   남자   91   90   89   80
희영  100  100  100  100  100  100

## #04. 열 추가하기

### 1. 리스트로 열 추가하기

- 모든 행에 대한 값을 순서대로 나열한다.
- 기존의 행과 비교하여 추가되는 값이 부족하거나 초과하면 에러 발생
- 빈값을 추가하고자 하는 경우 해당 위치에 `None`이라고 명시

In [18]:
리스트열추가DF = origin.copy()
리스트열추가DF['한국사'] = [72, 56, 90, None,92, 90, 75, 80, 60]
리스트열추가DF

    학년  성별  국어   영어  수학  과학    한국사
이름
철수   1  남자  98   77  88  64 72.000
영희   2  여자  88  120  62  72 56.000
민철   1  남자  92   70  83  79 90.000
수현   3  여자  63   60  31  71    NaN
호영   4  남자  75   50  90  88 92.000
영호   4  남자  80   88  91  72 90.000
용식   2  남자  82   88  79  90 75.000
나영   1  여자  90   92  81  95 80.000
석영   1  남자  91   90  89  80 60.000

### 2. 딕셔너리로 열 추가하기

- 추가되지 않을 행은 명시하지 않는다.
- 데이터프레임에 존재하지 않는 인덱스가 포함될 경우 해당 값을 버린다.
- 명시되지 않은 행은 빈값(`NaN`)으로 설정된다.

In [20]:
딕셔너리열추가DF = origin.copy()
딕셔너리열추가DF['세계사'] = {"철수": 90, "영희": 88, "민철":72, "수현":56, "정우":90, "준명": 100, "용식":77, "나영":95, "석영":54}
딕셔너리열추가DF

    학년  성별  국어   영어  수학  과학    세계사
이름
철수   1  남자  98   77  88  64 90.000
영희   2  여자  88  120  62  72 88.000
민철   1  남자  92   70  83  79 72.000
수현   3  여자  63   60  31  71 56.000
호영   4  남자  75   50  90  88    NaN
영호   4  남자  80   88  91  72    NaN
용식   2  남자  82   88  79  90 77.000
나영   1  여자  90   92  81  95 95.000
석영   1  남자  91   90  89  80 54.000

### 3. Series 객체로 추가하기

- 각 값이 연결될 행의 이름(index)를 지정해야 한다.
- 부분적으로 값을 비워 둘 수 있다.

In [21]:
시리즈열추가DF = origin.copy()
s = Series([72, 56, 90, 88], index=['철수', '민철', '호영', '용식'])
시리즈열추가DF['윤리'] = s
시리즈열추가DF

    학년  성별  국어   영어  수학  과학     윤리
이름
철수   1  남자  98   77  88  64 72.000
영희   2  여자  88  120  62  72    NaN
민철   1  남자  92   70  83  79 56.000
수현   3  여자  63   60  31  71    NaN
호영   4  남자  75   50  90  88 90.000
영호   4  남자  80   88  91  72    NaN
용식   2  남자  82   88  79  90 88.000
나영   1  여자  90   92  81  95    NaN
석영   1  남자  91   90  89  80    NaN

### 4. 기존의 열을 복사해서 열 추가하기

In [22]:
열복사DF = origin.copy()
열복사DF['체육'] = 열복사DF['과학']
열복사DF

    학년  성별  국어   영어  수학  과학  체육
이름
철수   1  남자  98   77  88  64  64
영희   2  여자  88  120  62  72  72
민철   1  남자  92   70  83  79  79
수현   3  여자  63   60  31  71  71
호영   4  남자  75   50  90  88  88
영호   4  남자  80   88  91  72  72
용식   2  남자  82   88  79  90  90
나영   1  여자  90   92  81  95  95
석영   1  남자  91   90  89  80  80

### 5. 단일 값으로 열 추가하기

In [23]:
단일값열추가DF = origin.copy()
단일값열추가DF['체육'] = 100
단일값열추가DF

    학년  성별  국어   영어  수학  과학   체육
이름
철수   1  남자  98   77  88  64  100
영희   2  여자  88  120  62  72  100
민철   1  남자  92   70  83  79  100
수현   3  여자  63   60  31  71  100
호영   4  남자  75   50  90  88  100
영호   4  남자  80   88  91  72  100
용식   2  남자  82   88  79  90  100
나영   1  여자  90   92  81  95  100
석영   1  남자  91   90  89  80  100

## #05. 행 삭제하기

### 1. 단일 행 삭제

- 추가는 원본 자체가 변하지만 삭제는 결과가 반영된 새로운 복사본이 생성된다.
- `drop()` 메서드도 `inplace=True` 파라미터 적용 가능

In [25]:
단일행삭제DF = origin.copy()
단일행삭제DF = 단일행삭제DF.drop(index="철수")
단일행삭제DF

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 다중 행 삭제

- 삭제할 행의 인덱스를 리스트로 지정한다.

In [26]:
다중행삭제DF = origin.copy()
다중행삭제DF = 다중행삭제DF.drop(index=['철수', '민철', '수현'])
다중행삭제DF

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 3. index에 대한 인덱싱으로 행 삭제

In [27]:
인덱싱행삭제DF = origin.copy()
인덱싱행삭제DF.index

Index(['철수', '영희', '민철', '수현', '호영', '영호', '용식', '나영', '석영'], dtype='str', name='이름')

In [28]:
인덱싱행삭제철수DF = origin.copy()
인덱싱행삭제철수DF = 인덱싱행삭제철수DF.drop(index=인덱싱행삭제철수DF.index[0])
인덱싱행삭제철수DF

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 4. index에 대한 슬라이싱으로 행 삭제

In [29]:
인덱싱행삭제슬DF = origin.copy()
인덱싱행삭제슬DF = 인덱싱행삭제슬DF.drop(index=인덱싱행삭제슬DF.index[0:7])
인덱싱행삭제슬DF

    학년  성별  국어  영어  수학  과학
이름
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

## #06 열 삭제

### 1. 단일 열 삭제

- 행 삭제는 `drop()` 메서드에 `index` 파라미터를 설정하고,     
  열 삭제는 `columns` 파라미터를 설정한다.

In [30]:
단일열삭제DF = origin.copy()
단일열삭제DF = 단일열삭제DF.drop(columns='학년')
단일열삭제DF

    성별  국어   영어  수학  과학
이름
철수  남자  98   77  88  64
영희  여자  88  120  62  72
민철  남자  92   70  83  79
수현  여자  63   60  31  71
호영  남자  75   50  90  88
영호  남자  80   88  91  72
용식  남자  82   88  79  90
나영  여자  90   92  81  95
석영  남자  91   90  89  80

### 2. 다중 열 삭제

- `columns` 파라미터에 삭제 대상 변수 이름을 리스트 타입으로 설정한다.

In [31]:
다중열삭제DF = origin.copy()
다중열삭제DF = 다중열삭제DF.drop(columns=['학년', '성별', '과학'])
다중열삭제DF

    국어   영어  수학
이름
철수  98   77  88
영희  88  120  62
민철  92   70  83
수현  63   60  31
호영  75   50  90
영호  80   88  91
용식  82   88  79
나영  90   92  81
석영  91   90  89

### 3. 컬럼명에 대한 인덱싱으로 열 삭제

In [33]:
인덱싱열삭제DF = origin.copy()
인덱싱열삭제DF = 인덱싱열삭제DF.drop(columns=인덱싱열삭제DF.columns[1])
인덱싱열삭제DF

    학년  국어   영어  수학  과학
이름
철수   1  98   77  88  64
영희   2  88  120  62  72
민철   1  92   70  83  79
수현   3  63   60  31  71
호영   4  75   50  90  88
영호   4  80   88  91  72
용식   2  82   88  79  90
나영   1  90   92  81  95
석영   1  91   90  89  80

### 4. 컬럼명에 대한 슬라이싱으로 열 삭제

In [ ]:
인덱싱열삭제슬DF = origin.copy()
인덱싱열삭제슬DF = 인덱싱열삭제슬DF.drop(columns=인덱싱열삭제슬DF.columns[2:4])
인덱싱열삭제슬DF

    학년  성별  수학  과학
이름
철수   1  남자  88  64
영희   2  여자  62  72
민철   1  남자  83  79
수현   3  여자  31  71
호영   4  남자  90  88
영호   4  남자  91  72
용식   2  남자  79  90
나영   1  여자  81  95
석영   1  남자  89  80

## #07. 축을 지정하여 행˙열 삭제

### 1. 축(`axis`)를 설정한 단일 행 삭제 방법

- 파라미터 이름을 지정하지 않을 경우 `index`이름으로 처리됨

In [36]:
축단일행삭제DF = origin.copy()
축단일행삭제DF.drop('철수')
축단일행삭제DF

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 축(axis)를 설정한 다중 행 삭제 방법

   여러 행을 삭제할 경우 인덱스 이름을 리스트로 전달

In [37]:
축다중행삭제DF = origin.copy()
축다중행삭제DF = 축다중행삭제DF.drop(['철수', '영희', '민철', '수현'])
축다중행삭제DF

    학년  성별  국어  영어  수학  과학
이름
호영   4  남자  75  50  90  88
영호   4  남자  80  88  91  72
용식   2  남자  82  88  79  90
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

### 3. 축(aixs)를 설정한 열 삭제 방법

   열을 삭제할 경우 축을 설정 (기본값=`0`, 행)

In [53]:
축열삭제DF = origin.copy()
축열삭제DF = 축열삭제DF.drop(['학년', '성별'], axis=1)
축열삭제DF

    국어   영어  수학  과학
이름
철수  98   77  88  64
영희  88  120  62  72
민철  92   70  83  79
수현  63   60  31  71
호영  75   50  90  88
영호  80   88  91  72
용식  82   88  79  90
나영  90   92  81  95
석영  91   90  89  80

In [ ]:
#당신은 신비한 생물을 연구하는 비밀 연구소의 신입 데이터 분석가입니다.
# 연구원들이 수기로 작성하던 관찰 기록을 처음으로 디지털화했지만, 데이터가 엉망진창입니다.
# 당신의 임무는 이 데이터를 깔끔하게 정리하여 곧 있을 학회 발표 자료로 만드는 것입니다.
# monsters 데이터셋을 DataFrame으로 불러온 후, 아래의 요구사항에 따라 데이터를 수정하고 최종겨과를 출력하세요.
# 1. 데이터의 첫인상 : 가장 먼저 데이터의 기본적인 정보(info)를 파악
# 2. 쓸모없는 정보 삭제 : last_seen열은 이번 발표에 필요없는 정보입니다. 해당 열을 데이터에서 삭제하세요.
# 3. 신규 개체 추가 : 최근 'M021' ID를 가진 신규 개체 'Kelpie'가 발견되었습니다. 아래 정보를 가진 행을 Series 객체로 생성한 후 DataFrame에 새로 추가하세요. 이 개체의 'weigt'는 측정되지 않았습니다.
# - '몬스터 고유 ID' : 'M021'      - '키' : 2.2m
# - '생물 종' : 'Kelpie'           - '위험 등급' : 'Medium'
# - '서식지' : 'Lake'
# 4. 데이터 오류 수정 : 'M004' 개체는 사실 'M003' 개체를 잘못 기록한 것입니다. 'M004'행의 모든 데이터를 'M003'행의 데이터와 동일하게 수정한 후, 'M004'행의 ID를 'M003_copy'로 변경하세요.
# 5. 최종보고서용 정렬 : 발표자료는 monster_id, caution_level, species, habitat, height, weight 순서로 열이 정렬되어야 합니다. 최종 DataFrame의 열 순서를 이 순서에 맞게 재배치하세요.

In [ ]:
# 0. 불러오기
from jussam import load_data
from pandas import Series

In [ ]:
# 1. 데이터의 첫인상
data = load_data('monsters')
data.info()
# 2. 쓸모없는 정보 삭제
dropdf = data.copy()
dropdf2 = datadf.drop(['last'])

📚 신비한 생물 연구소의 몬스터 데이터

    field          description
--  -------------  ----------------------
 0  monster_id     몬스터 고유 ID(인덱스)
 1  last_seen      마지막으로 관찰된 날짜
 2  species        생물 종
 3  habitat        서식지
 4  height         키 (m)
 5  weight         몸무게 (kg)
 6  caution_level  위험 등급

<class 'pandas.DataFrame'>
Index: 20 entries, M001 to M020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   last_seen      20 non-null     datetime64[us]
 1   species        20 non-null     str
 2   habitat        20 non-null     str
 3   height         20 non-null     float64
 4   weight         20 non-null     float64
 5   caution_level  20 non-null     str
dtypes: datetime64[us](1), float64(2), str(3)
memory usage: 1.5 KB

            last_seen   species   habitat  height    weight caution_level
monster_id
M001       2024-01-15   Griffin  Mountain   2.500   150.500          High
M002       2024-02-20   Unicorn    Forest   2.100   120.000           Low
M003       2024-03-10    Dragon   Volcano  15.200  5500.000     Very High
M004       2024-03-12    Dragon   Volcano  14.800  5300.000     Very High
M005       2024-04-05    Kraken     Ocean  30.500 15000.000          High
M006       2024-05-21   Phoenix    Desert   1.800    25.500        Medium
M007       2024-06-30   Mermaid     Ocean   1.900    65.500           Low
M008       2024-07-14    Goblin      Cave   1.100    40.200        Medium
M009       2024-08-01     Fairy    Forest   0.300     0.500           Low
M010       2024-09-10     Hydra     Swamp   5.500   800.000          High
M011       2024-10-02   Cyclops    Island   8.200  2500.000          High
M012       2024-11-18     Gnome    Garden   0.400     5.100           Low
M013       2024-12-25      Yeti  Mountain   3.500   300.000        Medium
M014       2025-01-20    Sphinx    Desert   2.800   180.000        Medium
M015       2025-02-15   Banshee     Ruins   1.700    45.000          High
M016       2025-03-22  Werewolf    Forest   2.300   110.000          High
M017       2025-04-18   Vampire    Castle   1.800    75.000          High
M018       2025-05-30   Chimera  Mountain   3.100   450.000     Very High
M019       2025-06-11  Basilisk     Sewer   4.000   200.000     Very High
M020       2025-07-07  Gargoyle   Rooftop   2.000   500.000        Medium